services:
  Mooc.MongoConfig:
    factory:
      class: ../../../../../Contexts/Mooc/Shared/infraestructure/mongo/persistence/MongoConfigFactory
      method: 'createConfig'
  Mooc.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConnectionManager'
    arguments: ["mooc", '@Mooc.MongoConfig']
  Mooc.Courses.application.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ["@Mooc.Courses.domain.CourseRepository"]

  Mooc.Courses.domain.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourserepository
    arguments: ["@Mooc.ConnectionManager"]
    # Mooc.Courses.domain.CourseRepository:
    # class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/FileCourseRepository
    # arguments: [""]