version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - type: bind
        source: persist/mongo
        target: /data/db
    ports:
      - 27017:27017
volumes:
  mongodb: