name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Android: 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  Appcenter:
    runs-on: ubuntu-latest
    needs: Android
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: App Center
        uses: wzieba/AppCenter-Github-Action@v1.0
        with: 
          appName: Ch-DemoOrg by username
          token: ${{secrets.AppCenterAPIToken}}
          group: alphatesters
          file: AwesomeApp/AwesomeApp.Android/bin/Debug/com.companyname.AwesomeApp.apk
          relaseNotes: "demo test"
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, Wold!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          echo other   
