name: manualworkflow
on:
  workflow_dispatch:
    inputs: 
      name:
        description: 'jordan huaman'
        required: true
        default: 'Jordan'
      country:
        description: 'contry'
        required: false
jobs:
  greetuser:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hi ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.country }}!"